name: faved
services:
  apache-php:
    container_name: faved-web-app
    image: denho/faved
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - temp-data:/tmp/
      - storage:/var/www/html/storage/
      - apache-conf:/etc/apache2/sites-enabled/
      - certbot-conf:/etc/letsencrypt/
    ports:
      - "${PORT:-8080}:80"
      - "${SSL_PORT:-8443}:443"

volumes:
  temp-data:
  storage:
  apache-conf:
  certbot-conf:
