name: faved-dev
services:
  apache-php:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    working_dir: /var/www/html
    volumes:
      - temp-data:/tmp/
      - .:/var/www/html:delegated
      - ./apache-conf:/etc/apache2/sites-enabled:delegated
      - ./certbot-conf:/etc/letsencrypt:delegated
    ports:
      - "${BACKEND_PORT:-8000}:80"
  node:
    image: node:24
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./frontend:/var/www/html:delegated
      - ./public/dist/:/var/www/html/dist/:delegated
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    environment:
      - "BACKEND_PORT=${BACKEND_PORT:-8000}"
    command: sh -c "npm install && npm run dev -- --host"
  composer:
      image: composer/composer
      restart: "no"
      working_dir: /app
      volumes:
        - .:/app:delegated
      command: ["composer", "install"]

volumes:
  temp-data: